name: ecommerce_bloc_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #map
  google_maps_flutter: ^2.10.1
  flutter_google_places: ^0.3.0
  #firebase
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  #image
  image_picker: ^1.1.2
  image_gallery_saver: ^2.0.3
  file_picker: ^9.0.2
  #bloc
  flutter_bloc: ^9.0.0
  #provider
  provider: ^6.1.2
  #payment
  square_in_app_payments: ^1.7.10
  #data
  equatable: ^2.0.7
  meta: ^1.15.0
  intl: ^0.19.0
  rxdart: ^0.26.0
  #UI
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  #Others
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9 # Help us to use svg in our app
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/locale/

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
