// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsdvGP1QJsQS4McSPT_muuEScFcDazgBQ',
    appId: '1:55266420712:android:c47f6fa874706cbf33665d',
    messagingSenderId: '55266420712',
    projectId: 'ez-ecommerce-4be93',
    storageBucket: 'ez-ecommerce-4be93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD48ZM4e4vIY-vpRfTs5ugq8tAKrJ7xAho',
    appId: '1:55266420712:ios:754f49b687a0d44b33665d',
    messagingSenderId: '55266420712',
    projectId: 'ez-ecommerce-4be93',
    storageBucket: 'ez-ecommerce-4be93.firebasestorage.app',
    androidClientId: '55266420712-kshknpu241s6btdrgmjdrbg0qvm542gm.apps.googleusercontent.com',
    iosClientId: '55266420712-7a95pbc4bvmsq48kod2at6svnmcchf7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBlocApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeYp_g-DUStfnRZMkh5SO8IG7QEK0D-o',
    appId: '1:55266420712:web:b293aa9ef7b7744033665d',
    messagingSenderId: '55266420712',
    projectId: 'ez-ecommerce-4be93',
    authDomain: 'ez-ecommerce-4be93.firebaseapp.com',
    storageBucket: 'ez-ecommerce-4be93.firebasestorage.app',
    measurementId: 'G-09J40QVZ92',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD48ZM4e4vIY-vpRfTs5ugq8tAKrJ7xAho',
    appId: '1:55266420712:ios:754f49b687a0d44b33665d',
    messagingSenderId: '55266420712',
    projectId: 'ez-ecommerce-4be93',
    storageBucket: 'ez-ecommerce-4be93.firebasestorage.app',
    androidClientId: '55266420712-kshknpu241s6btdrgmjdrbg0qvm542gm.apps.googleusercontent.com',
    iosClientId: '55266420712-7a95pbc4bvmsq48kod2at6svnmcchf7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBlocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOeYp_g-DUStfnRZMkh5SO8IG7QEK0D-o',
    appId: '1:55266420712:web:2dd65dd3b200386833665d',
    messagingSenderId: '55266420712',
    projectId: 'ez-ecommerce-4be93',
    authDomain: 'ez-ecommerce-4be93.firebaseapp.com',
    storageBucket: 'ez-ecommerce-4be93.firebasestorage.app',
    measurementId: 'G-KCK9GXV03S',
  );

}